INSTALAÇÃO E EXECUÇÃO BÁSICA

1 - HABILITAR DOIS CONTAINERS (PODE DOCKER/SINGULARITY) COM UBUNTU 24.04 DE SISTEMA, AMBOS COM A PROTA 8687 LIBERADAS
2 - APÓS HABILITAR, TRANSFERIR OS ARQUIVOS 'RUN' PARA CADA UM (UM VAI SER O SERVIDOR QUE IRÁ RECEBER OS COMANDOS SOLICITADOS, O OUTRO SERÁ QUEM EXECUTARÁ AS TAREFAS, SENOD CONHECIDO COMO 'WORKER')
3 - TRANSFERIR O ARQUIVO 'DASK_TEST.PY' PARA O CONTAINER SERVIDOR
4 - EXECUTAR O ARQUIVO DO PYTHON NO CONTAINER SERVIDOR

